name: Redpack
main: com.Little_Snow_.Redpack.Main
version: 1.1
author: Little_Snow_
softdepend: [Vault]
commands: 
  redpack:
    description: redpack main commands
    usage: /<command>
    permission: redpack.main
    permission-message: §c你需要redpack.main权限来执行此命令
  hb:
    description: redpack main commands
    usage: /<command>
    permission: redpack.use
    permission-message: §c你需要redpack.use权限来执行此命令
permissions: 
  redpack.main: 
    description: 允许使用/redpack
    default: true
  redpack.use:
    description: 允许使用/hb
    default: true