name: Redpack
version: 1.0
authors: [chenhao]
main: com.Little_Snow_.Redpack.Main
softdepend: [Vault]

commands:
  redpack:
    description: Displays information about redpack
    usage: |
           /<command> - Displays Vault information
  hb:
    description: use redpack
    usage: |
           /<command> [economy1] [economy2]
permissions:
  redpack.main:
    description: Notifies the player when vault is in need of an update.
    default: op
  redpack.use:
    description: Notifies the player when vault is in need of an update.
    default: true